export type HelpTopic = {
  id: string;
  title: string;
  summary: string;
  content: string[];
  blockable?: boolean; // If true, topic can be hidden from employees unless granted
  route?: string;
  section?: 'menu' | 'dashboard';
};

// Admin help split into full coverage of slide-out Menu and Admin Dashboard actions
export const adminMenuTopics: HelpTopic[] = [
  {
    id: 'chemical-workflow',
    title: 'Chemical Workflow',
    summary: 'Master the full lifecycle of chemical management—from library selection to bottle labeling and job tracking.',
    content: [
      '**The Professional Chemical Workflow**: This guide explains how to properly manage chemicals across the entire system.',
      '',
      '🧪 **Step 1: The Chemical Library**',
      'The process begins in the **Chemical Cards** page. Here, you can search our entire arsenal of products. Each card contains vital data about: ',
      '• **Safety & Hazards**: Proper protection and warnings.',
      '• **Mix Ratios**: Task-specific dilution rates for different surfaces.',
      '• **Gallery**: Real-world photos of the product and its results.',
      '',
      '🏷️ **Step 2: Designing the Label**',
      'Once a chemical is selected, use the **Bottle Label Maker** to create custom identifiers for your workspace:',
      '• **AI Automation**: Use "AI FIX" to generate concise, professional descriptions instantly.',
      '• **Task-Specific Ratios**: The label maker pulls the "Best Ratio" automatically based on your task (Interior, Exterior, etc.).',
      '• **Verification**: Use the real-time preview to ensure all safety warnings and primary dilution ratios are clearly visible.',
      '',
      '📦 **Step 3: Inventory & Labels**',
      'After printing your high-contrast label, ensuring it matches the physical stock:',
      '• **Inventory Updates**: Log restocks or bulk adjustments in the Inventory Control section.',
      '• **Saved Templates**: Save your custom label designs to quickly reprint them when bottles are refilled or replaced.',
      '',
      '📋 **Step 4: Job Execution**',
      'During a **Service Checklist**, the system tracks chemical usage:',
      '• **Usage Logging**: When you finalize a job, the system can automatically deduct material usage if configured.',
      '• **Reference**: Field crews can access the Chemical library at any time from their mobile devices to check safety data or mix instructions.',
      '',
      '🎯 **Why this matters**: Consistent labeling prevents cross-contamination, ensures surface safety, and maintains a professional laboratory-grade presentation for clients.',
    ],
    route: '/chemicals',
    section: 'menu',
  },
  {
    id: 'chemical-label-maker',
    title: 'Chemical Label Maker',
    summary: 'Professional label creation with AI assistance, task-specific ratios, and multi-label splitting.',
    content: [
      '**Overview**: The Chemical Label Maker allows you to design and print high-contrast, professional-grade labels for any bottle size (4oz to 32oz).',
      '',
      '🤖 **AI Auto-Fix & Intelligence**:',
      '• **Auto-Fix**: Click the "AI FIX" button to automatically condense long descriptions and pull usage instructions directly from the chemical data.',
      '• **Scenario Detection**: The system identifies and icons specific ratios for **Interiors (🛋️)**, **Exterior (🚗)**, **Wheels (🛞)**, **Bug Removal (🪲)**, and **Very Dirty (💪)**.',
      '• **Scenario Filters**: Use specialized filters (Interior, Exterior, Very Dirty, Slightly Dirty) to control exactly which mix ratios appear in your dilution table. This allows you to generate labels tailored to the task at hand.',
      '',
      '📏 **Layout & Customization**:',
      '• **Dynamic Toggles**: Every single item on the label (Images, Brand, Summary, Ratios, Instructions, Safety Alerts) is controlled by a toggle. If you turn a toggle off, it is removed from the editor and will NOT be printed.',
      '• **Select All/None**: Use the helper button in the Toggle list to quickly turn all sections on or off.',
      '• **Split Labels**: Enable "Split Labels" to generate two separate stickers—one for primary branding and one for technical usage/ratios.',
      '• **Freeform Notes**: Add custom information like customer names or special mix dates directly onto the label.',
      '• **Blank Form**: Adds a dedicated space with dotted lines for hand-writing notes with a Sharpie after printing.',
      '',
      '👁️ **Accessibility & Printing**:',
      '• **Ultra-Wide Experience**: Optimized for 32" monitors with an expanded 1700px workspace, larger fonts, and high-visibility inputs.',
      '• **Ink Saver (Light Mode)**: Default setting that forces black text on white backgrounds to save printer ink.',
      '• **Bold Mode**: Increases all font weights for better legibility.',
      '• **Template Selector**: Supports 4oz, 8oz, 16oz, 24oz, 32oz, and Multi-Purpose Sticker sizes.',
      '',
      '💾 **Saved Custom Designs**:',
      '• **Quick Save**: Store your complete configuration (toggles, text, ratios, and image) to quickly reproduce labels in the future.',
      '• **Management**: Access saved templates from the sidebar list. Hover over any design to delete it.',
      '',
      '📁 **Saving & PDF**:',
      '• **Save PDF**: Downloads a high-resolution PDF file.',
      '• **Print Label**: Opens the system print dialog. Ensure you select "Light Mode" for ink saving.',
    ],
    route: '/inventory-control',
    section: 'menu',
  },
  {
    id: 'admin-dashboard',
    title: 'Admin Dashboard',
    summary: 'Central control hub for alerts, jobs, KPIs, and quick admin actions.',
    content: [
      'Overview cards show unpaid invoices, inventory alerts, task updates, and file changes.',
      'Quick links provide access to Customer profiles, Invoicing, Accounting, Payroll, Inventory, File Manager, Reports, and more.',
      '**Scenario Builder**: Quick access shortcut in the top right to create custom pricing quotes.',
      'Menu Visibility Controls allow hiding or showing dashboard tiles in the sidebar and menus.',
      'User Administration provides full user management: create, update, impersonate, and delete employees.',
      'Employee Management modal focuses on employee operations with search and edit capabilities.',
      'Web Administration integrates vehicle types, FAQs, contact info, and About sections management.',
      '**Phone Assistant**: Direct access to branded scenario scripts and consistent package inclusions.',
    ],
    route: '/admin-dashboard',
    section: 'menu',
  },
  {
    id: 'customers',
    title: 'Customers',
    summary: 'Manage customer profiles, search, and related records.',
    content: [
      'Create and update customer profiles including contact details and service history.',
      'Search and link invoices and tasks to customers.',
      'Import and export customer data using provided tools.',
      '**Archiving**: You can archive inactive customers using the "Archive" button. Toggle "Show Archived" to view or restore them.',
    ],
    route: '/search-customer',
    section: 'menu',
  },
  {
    id: 'prospects',
    title: 'Prospects',
    summary: 'Track potential clients and convert them to customers.',
    content: [
      'Add new prospects and track their vehicle interest and source.',
      'Convert prospects to full customers with one click when they book a job.',
      '**Archiving**: Archive prospects that are no longer active. Use the "Show Archived" filter to manage them.',
      'Generate PDF reports of your current prospect list.',
    ],
    route: '/prospects',
    section: 'menu',
  },
  {
    id: 'photo-system',
    title: 'Photo & Media Management System',
    summary: 'Two-layer photo system for customer profiles and vehicle-specific media.',
    content: [
      '**Overview**: The app uses a two-layer system to organize photos separately for customers and their vehicles.',
      '',
      '🧑 **Layer 1: Customer Profile Media**',
      'Top section labeled \"GENERAL PROFILE MEDIA (Account Level)\"',
      '',
      '**What Goes Here**:',
      '• Customer headshots and ID photos',
      '• Profile pictures',
      '• Any photos of the person themselves',
      '',
      '**Categories**:',
      '• PROFILE / GENERAL - General customer photos',
      '• MISC BEFORE - Photos before working with your company',
      '• MISC AFTER - Photos showing results/after service',
      '',
      '**Storage**: Saved to customers table (general_photos, before_photos, after_photos)',
      '**Persistence**: Stays even if customer doesn\'t have a vehicle',
      '',
      '🚗 **Layer 2: Vehicle-Specific Media**',
      'Bottom section labeled \"VEHICLE-SPECIFIC MEDIA\"',
      '',
      '**What Goes Here**:',
      '• Before/After detailing photos',
      '• Vehicle condition documentation',
      '• Damage photos',
      '• General car photos',
      '',
      '**Categories** (per vehicle):',
      '• BEFORE PHOTO - Vehicle condition before service',
      '• AFTER PHOTO - Vehicle condition after detailing',
      '• GENERAL PHOTO - General vehicle photos',
      '',
      '**Storage**: Saved to vehicles table linked to customer',
      '**Independence**: Each vehicle has its own photo gallery',
      '',
      '🎯 **Real-World Example**:',
      'Serge Michaud has 2 vehicles:',
      '',
      '1. Upload Serge\'s ID photo in top section',
      '   → Shows in Media Library under "Serge Michaud (Customer Photos)"',
      '',
      '2. Upload before/after photos for 2020 Toyota Versa',
      '   → Shows under "Serge Michaud → Toyota Versa"',
      '',
      '3. Upload different photos for 2018 Ram 1500',
      '   → Shows under "Serge Michaud → Ram 1500"',
      '',
      'Result: 3 separate photo galleries, all organized under Serge',
      '',
      '💡 **Best Practices**:',
      '',
      '**Use Customer Photos For**:',
      '✅ Customer ID/license for records',
      '✅ Customer with their vehicle (person visible)',
      '✅ Profile pictures for identification',
      '',
      '**Use Vehicle Photos For**:',
      '✅ Before/after detailing work',
      '✅ Vehicle condition documentation',
      '✅ Damage or scratch documentation',
      '✅ Progress photos during service',
      '',
      '**Organizing Tips**:',
      '• Always add vehicle first before uploading vehicle photos',
      '• Upload before photos BEFORE starting work',
      '• Upload after photos immediately after completion',
      '• Customer photos are optional but helpful',
      '',
      '🔍 **Troubleshooting**:',
      '',
      '**"I uploaded photos but don\'t see them in Media Library"**',
      '• Hard refresh the page (Ctrl + Shift + R)',
      '• Verify you clicked "Save Prospect" or "Save Customer"',
      '• Check photos in customer editor - they should persist',
      '',
      '**"Photos disappeared after saving"**',
      '• Check browser console for errors',
      '• Verify Supabase storage permissions',
      '• Ensure customer_id is correctly linked to vehicle',
      '',
      '**"Can\'t upload photos"**',
      '• Check file size (max 10MB per photo)',
      '• Verify supported formats: JPG, PNG, WebP',
      '• Ensure Supabase storage buckets exist',
      '',
      '📊 **Data Flow**:',
      '1. Upload photo in Customer Editor',
      '2. Photo saved to Supabase Storage bucket',
      '3. Photo URL saved to database',
      '4. Media Library queries database',
      '5. Photos displayed grouped by customer/vehicle',
      '',
      '**Quick Reference**:',
      'Customer photo → Top section → customers table',
      'Vehicle photo → Bottom section → vehicles table',
      'View all → Media Library → Organized by customer',
      '',
      'See also: "Media Library Gallery" for viewing all photos',
    ],
    route: '/prospects',
    section: 'menu',
  },
  {
    id: 'media-library',
    title: 'Media Library Gallery',
    summary: 'View all customer and vehicle photos organized and searchable.',
    content: [
      '**Overview**: The Media Library shows all photos from all customers and vehicles in one place.',
      '',
      '**Access**: Main navigation → "Media Library"',
      '',
      '📂 **View Modes**:',
      '',
      '**Organized View** (Default):',
      '• Photos grouped by customer and vehicle',
      '• Expandable accordions for each customer',
      '• Shows customer-level photos separately from vehicles',
      '• Each vehicle has its own photo section',
      '',
      '**All Photos View**:',
      '• Continuous grid of all media',
      '• No grouping - just all photos together',
      '',
      '**Flat Gallery**:',
      '• Scrollable view without accordion expansion',
      '• Fast browsing of all media',
      '',
      '🔍 **Search & Filter**:',
      '',
      '**Search Bar**:',
      '• Search by customer name',
      '• Filter by vehicle make/model',
      '• Search updates results instantly',
      '',
      '**Media Types**:',
      '• All Photos (default)',
      '• Before Photos only',
      '• After Photos only',
      '• General Photos only',
      '',
      '**View Controls**:',
      '• Expand All - Opens all customer/vehicle sections',
      '• Collapse All - Closes all sections',
      '• Perfect for quick browsing',
      '',
      '📸 **Photo Organization**:',
      '',
      '**Customer Level**:',
      'Shows under "Customer Name (Customer Photos)"',
      '• Profile / General photos',
      '• Misc Before photos',
      '• Misc After photos',
      '',
      '**Vehicle Level**:',
      'Shows under "Customer Name → Make Model"',
      '• General vehicle photos',
      '• Before detailing photos',
      '• After detailing photos',
      '• Video links (if any)',
      '',
      '🎯 **Example Organization**:',
      '',
      'Serge Michaud',
      '├─ Customer Photos (1 photo)',
      '├─ Toyota Versa',
      '│  ├─ Before Photos (2)',
      '│  └─ After Photos (3)',
      '└─ Ram 1500',
      '   ├─ Before Photos (1)',
      '   └─ After Photos (2)',
      '',
      '**Why Photos Appear Here**:',
      '✅ Uploaded via Customer/Prospect editor',
      '✅ Saved successfully to Supabase',
      '✅ Linked to customer or vehicle record',
      '',
      '**Why Photos Might Not Show**:',
      '❌ No photos uploaded yet',
      '❌ Photos on different vehicle (check other vehicles)',
      '❌ Customer-level photos only (check customer section, not vehicle)',
      '❌ Not saved - clicked "Cancel" instead of "Save Prospect"',
      '',
      '💡 **Usage Tips**:',
      '',
      '**For Quick Lookups**:',
      '1. Use search bar to find customer',
      '2. Expand their section',
      '3. View all photos for that customer and their vehicles',
      '',
      '**For Comparisons**:',
      '1. Use "Flat Gallery" view',
      '2. Scroll through all before/after photos',
      '3. Great for showcasing work',
      '',
      '**For Specific Types**:',
      '1. Switch to "Before Photos" or "After Photos" tab',
      '2. See only that type across all customers',
      '3. Perfect for creating marketing materials',
      '',
      '**Mobile View**:',
      '• Tabs scroll horizontally',
      '• Photo grid adjusts for smaller screens',
      '• Expand/collapse works the same',
      '',
      '🔗 **Integration**:',
      '',
      '**Upload Flow**:',
      'Prospects/Customers → Edit → Upload Photos → Save → Shows in Media Library',
      '',
      '**Data Source**:',
      '• Customer photos from: customers.general_photos, .before_photos, .after_photos',
      '• Vehicle photos from: vehicles.general_photos, .before_photos, .after_photos',
      '',
      '**Technical Notes**:',
      '• Photos stored in Supabase Storage',
      '• URLs saved in database arrays',
      '• Real-time sync with customer/vehicle records',
      '• Supports JPG, PNG, WebP formats',
      '',
      'See also: "Photo & Media Management System" for upload instructions',
    ],
    route: '/vehicle-gallery',
    section: 'menu',
  },
  {
    id: 'invoicing',
    title: 'Invoicing',
    summary: 'Generate and manage invoices, review payment status.',
    content: [
      'Create invoices from jobs; edit line items and taxes.',
      'Track unpaid invoices and follow up via alerts or email.',
      'Export summaries for accounting and reporting needs.',
    ],
    route: '/invoicing',
    section: 'menu',
  },
  {
    id: 'estimates',
    title: 'Estimates',
    summary: 'Manage inbound estimate requests and outbound quotes.',
    content: [
      'Inbound requests from "Book Now" auto-generate PDFs in File Manager.',
      'Review request details, convert to jobs, or communicate with customers.',
      'System simulates emails for local testing and archives them.',
    ],
    route: '/estimates',
    section: 'menu',
  },
  {
    id: 'accounting',
    title: 'Accounting',
    summary: 'View revenue reports and reconcile with completed jobs.',
    content: [
      'Review KPIs such as total revenue and job statuses.',
      'Generate period-based summaries for business insights.',
      'Integrate with invoicing data for consistency.',
    ],
    route: '/accounting',
    section: 'menu',
  },
  {
    id: 'company-budget',
    title: 'Company Budget',
    summary: 'Track expenses, visualize P/L status, and monitor monthly timelines.',
    content: [
      'Visual P/L cards use green/red/blue coding for instant status recognition.',
      'Input fixed and variable costs to forecast profitability.',
      'Responsive line graphs allow monthly timeline tracking on all devices.',
    ],
    route: '/company-budget',
    section: 'menu',
  },
  {
    id: 'payroll',
    title: 'Payroll',
    summary: 'Manage employee payouts, hours, and job-based compensation.',
    content: [
      'Record hours and track job completions that affect pay.',
      'Dismiss related alerts when records are reviewed.',
      'Export payroll summaries.',
    ],
    route: '/payroll',
    section: 'menu',
  },
  {
    id: 'inventory-control',
    title: 'Inventory Control',
    summary: 'Track chemical/material levels, view usage history, and manage tools.',
    content: [
      'Dashboards show stock levels with low-stock alerts.',
      'Usage History tracks all consumption automatically from Jobs.',
      "Material Updates: Use the 'Material Updates' button to log bulk usage or adjustments (e.g. spills, restock) not tied to a specific job.",
      'Edit History: Click any Usage history item to view or edit notes.',
    ],
    route: '/inventory-control',
    section: 'menu',
  },
  {
    id: 'inventory',
    title: 'Inventory Control',
    summary: 'Maintain supply levels, set thresholds, and track usage.',
    content: [
      'Monitor critical inventory counts and restock reminders in alerts.',
      '**Strict Classification**: Items must be explicitly marked as "Tool" (Assets/Equipment) or "Material" (Consumables/Supplies).',
      '**Lifecycle Distinction**: Assets are durable/long-term; Consumables are one-time use or depletable.',
      '**Powered Equipment**: All powered machinery must be classified as a Tool for proper maintenance tracking.',
      'Update item details and categories with unified modals.',
      'Link inventory usage to jobs for accurate tracking.',
      'Responsive tables ensure full visibility on mobile devices.',
    ],
    route: '/inventory-control',
    section: 'menu',
  },
  {
    id: 'file-manager',
    title: 'File Manager',
    summary: 'Archive PDFs and documents like employee communications and certificates.',
    content: [
      'Save generated PDFs from Employee Contact and Certificates flows.',
      'Use alerts to track new files; dismiss when reviewed.',
      'Organize files by folder paths and metadata for quick retrieval.',
      'Responsive layout ensures file lists are accessible on any device.',
      'New automated folders for Estimates, Vehicle Classifications, and Inventory Reports.',
    ],
    route: '/file-manager',
    section: 'menu',
  },
  {
    id: 'team-chat',
    title: 'Team Chat',
    summary: 'Real-time messaging for the whole team and guest users.',
    content: [
      'Direct Messages: Private secure chats between employees and admins.',
      'Group Chat: General channels for team-wide announcements.',
      'Guest Chat: Communicate with customers or guests via secure links.',
      'Notifications: Badges indicate unread messages instantly.',
    ],
    route: '/team-chat',
    section: 'menu',
  },
  {
    id: 'tasks',
    title: 'Tasks (Todo)',
    summary: 'Plan work with multi-assignee tasks, comments, statuses, and read receipts.',
    content: [
      'Create tasks via quick add or detailed editor; set priority and due dates.',
      'Assign one or more employees; employees see only their assigned tasks.',
      'Use Kanban, List, or Calendar views and filters like Mine, Overdue, Today, Upcoming.',
      'Employees update status and post comments; admins get alerts on comments and completion.',
      'Read receipts capture who has viewed tasks and when.',
    ],
    route: '/tasks',
    section: 'menu',
  },
  {
    id: 'alerts',
    title: 'Alerts & Notifications',
    summary: 'System alerts for admins and employee notifications underpin proactive workflows.',
    content: [
      'Admin alerts include overdue tasks, todo updates and comments, and file manager events.',
      'Employee notifications deliver direct notice for new/updated task assignments.',
      'Notification Bell shows unread counts and provides quick navigation.',
    ],
    section: 'menu',
  },
  {
    id: 'users-roles',
    title: 'Users & Roles',
    summary: 'Centralized user management for admins, employees, customers, and prospects.',
    content: [
      '**Overview**: Manage all user types in one place with quick creation, deletion, and overview stats.',
      '**5 Stats Cards**: View counts for Admins (🟡), Employees (🔵), Customers (🟣), Prospects (🟠), and Total Users (🟢).',
      '**Refresh Button**: Manually refresh all user data anytime with visual loading indicator.',
      '',
      '**When to Use Users & Roles**:',
      '✅ Quick user creation (any type)',
      '✅ Delete users safely',
      '✅ View stats and overview',
      '✅ Bulk management tasks',
      '',
      '**Administrators Section (🟡 Amber)**:',
      '• Create admins via Edge Function (secure)',
      '• View admin list with roles and last update',
      '• Delete admins with confirmation',
      '• Search admins by name or email',
      '',
      '**Employees Section (🔵 Blue)**:',
      '• Onboard new employees quickly',
      '• Edit employee details inline',
      '• Delete employees with confirmation',
      '• Search employees by name or email',
      '',
      '**Customers Section (🟣 Purple)**:',
      '• Add customers with name, email, phone',
      '• Edit button navigates to Customer Profiles page',
      '• Delete customers (checks for vehicles first)',
      '• Search customers by name or email',
      '',
      '**Prospects Section (🟠 Orange)**:',
      '• Add prospects for lead tracking',
      '• Edit button navigates to Prospects page',
      '• Delete prospects (checks for vehicles first)',
      '• Search prospects by name or email',
      '',
      '**Safety Features**:',
      '✅ Delete Protection: Cannot delete customers/prospects with linked vehicles',
      '✅ Confirmation Dialogs: Always asks before deleting',
      '✅ Helpful Errors: Shows exactly what\'s wrong (e.g., "Customer has 3 vehicles linked")',
      '✅ Auto-Refresh: Tables update after creation/deletion',
      '',
      '**When NOT to Use Users & Roles**:',
      '❌ Detailed customer information → Use Customer Profiles',
      '❌ Vehicle management → Use Customer Profiles',
      '❌ Lead tracking/conversion → Use Prospects page',
      '❌ HR tasks/payroll → Use Company Employees',
      '',
      '**Pro Tips**:',
      '💡 Use Users & Roles for quick adds, dedicated pages for detailed work',
      '💡 Edit buttons navigate to the appropriate detailed page',
      '💡 Search works across all sections simultaneously',
      '💡 Color coding helps identify user types at a glance',
    ],
    route: '/user-management',
    section: 'menu',
  },
  {
    id: 'user-management-quick-tips',
    title: 'User Management - Quick Tips',
    summary: 'Quick reference guide for when to use each user management page.',
    content: [
      '**When to Use Each Page**:',
      '',
      '**🎯 Users & Roles (Operations Menu)**',
      'Use for: Quick admin tasks',
      '✅ Add new users (any type)',
      '✅ Delete users',
      '✅ View stats/overview',
      '✅ Bulk management',
      '❌ Don\'t use for: Detailed info, vehicles, bookings',
      '',
      '**👥 Customer Profiles**',
      'Use for: Customer details',
      '✅ Search customers',
      '✅ Manage vehicles',
      '✅ View booking history',
      '✅ Detailed customer info',
      '',
      '**🎯 Prospects**',
      'Use for: Sales & leads',
      '✅ Track leads',
      '✅ Lead source tracking',
      '✅ Follow-up management',
      '✅ Convert to customers',
      '',
      '**💼 Company Employees**',
      'Use for: HR tasks',
      '✅ Employee details',
      '✅ Contact information',
      '✅ Payroll management',
      '✅ Role management',
      '',
      '**Quick Reference**:',
      '• Add a new customer quickly → Users & Roles',
      '• Find customer\'s vehicles → Customer Profiles',
      '• Delete test data → Users & Roles',
      '• Track a lead → Prospects',
      '• Convert prospect to customer → Prospects',
      '• View employee pay rate → Company Employees',
      '• See user stats → Users & Roles',
      '• Search for a customer → Customer Profiles',
      '',
      '**Color Guide**:',
      '🟡 Amber = Admins',
      '🔵 Blue = Employees',
      '🟣 Purple = Customers',
      '🟠 Orange = Prospects',
      '🟢 Emerald = Total',
      '',
      '**Safety Features**:',
      '✅ Delete Protection - Can\'t delete customers/prospects with vehicles',
      '✅ Confirmation Dialogs - Always asks before deleting',
      '✅ Refresh Button - Manual data refresh anytime',
      '✅ Search Filters - Find users quickly',
      '',
      '**Pro Tips**:',
      '💡 Deleting Customers: If you get an error, they have vehicles. Delete vehicles first.',
      '💡 Prospects: Use the Prospects page for detailed lead tracking, Users & Roles for quick adds.',
      '💡 Refresh: Click the refresh button after creating users to see them immediately.',
      '💡 Navigation: Edit buttons take you to the detailed page for that user type.',
    ],
    route: '/user-management',
    section: 'menu',
  },
  {
    id: 'employees',
    title: 'Company Employees',
    summary: 'Comprehensive HR management for employee details, payroll, and roles.',
    content: [
      '**Overview**: Detailed employee management beyond basic user creation.',
      '',
      '**Employee Details**:',
      '• Full contact information (address, emergency contacts)',
      '• Role and position management',
      '• Department assignments',
      '• Hire date and employment status',
      '',
      '**Payroll Management**:',
      '• Pay rates and compensation',
      '• Hours tracking',
      '• Payment history',
      '• Integration with Payroll page',
      '',
      '**Schedule & Availability**:',
      '• Work schedule preferences',
      '• Time off requests',
      '• Availability windows',
      '• Integration with Staff Schedule',
      '',
      '**Performance & Notes**:',
      '• Performance reviews',
      '• Manager notes',
      '• Training completion',
      '• Certification tracking',
      '',
      '**When to Use Company Employees**:',
      '✅ HR tasks and employee records',
      '✅ Payroll and compensation',
      '✅ Detailed contact information',
      '✅ Performance management',
      '',
      '**When to Use Users & Roles Instead**:',
      '✅ Quick employee creation',
      '✅ Simple deletion',
      '✅ Overview stats',
      '',
      '**Features**:',
      'Create employees with comprehensive details',
      'Edit all employee information',
      'Impersonate employees to test role-based views',
      'Delete employees with confirmations',
      'Search and filter employee list',
      '',
      '**Integration**:',
      '• Links to Payroll for payment processing',
      '• Links to Staff Schedule for shift management',
      '• Links to Tasks for work assignments',
      '• Links to Training for certification tracking',
    ],
    route: '/company-employees',
    section: 'menu',
  },
  {
    id: 'website-admin',
    title: 'Website Administration',
    summary: 'Manage website-facing content: vehicle types, FAQs, contact info, and About.',
    content: [
      'Edit vehicle type catalog including names, descriptions, and pricing flags.',
      'Maintain FAQ items with question and answer content.',
      'Update contact information for public site and customer communications.',
      'Add About sections to present the company coherently.',
    ],
    route: '/website-admin',
    section: 'menu',
  },
  {
    id: 'vehicle-classification',
    title: 'Vehicle Classification',
    summary: 'Define vehicle sizes and pricing multipliers.',
    content: [
      'Categorize vehicles (sedan, SUV, truck) to standardize pricing.',
      'Export classification lists to PDF for shop reference.',
      'Link customers to specific classification profiles for accurate quoting.',
    ],
    route: '/vehicle-classification',
    section: 'menu',
  },
  {
    id: 'package-selection',
    title: 'Package Comparison Guide',
    summary: 'Visual aid for explaining service packages to clients.',
    content: [
      '**Prime Tier System**: Displays the standardized Prime Essential and Prime Elite tiers.',
      'Side-by-side comparison of features, pricing, and "What\'s Included".',
      '**Dynamic Sync**: Package details are pulled from the master service list, ensuring consistency between the website and admin tools.',
      'Use as a sales tool during client intake or phone calls.',
    ],
    route: '/package-selection',
    section: 'menu',
  },
  {
    id: 'website',
    title: 'Website',
    summary: 'Open the public site to view packages, add-ons, and tools.',
    content: [
      '**Prime Tiers**: The public site features the standardized Prime Essential and Prime Elite tiers.',
      '**Avg. Time Display**: Customers can see the "Average Time" for each package in the "Learn More" modals.',
      '**Booking Integration**: The search and selection process in the Book Now flow is fully synchronized with admin pricing.',
      'Use this entry to quickly access the public pricing and services pages.',
    ],
    route: '/',
    section: 'menu',
  },
  {
    id: 'training',
    title: 'Training & Exams',
    summary: 'Provide courses, exams, and orientation materials for employees.',
    content: [
      'Orientation modal outlines company overview, policies, and getting started guides.',
      'Training Manual and Exam flows reinforce best practices and certify employees.',
      'Certificates can be generated and archived in File Manager.',
    ],
    route: '/training-manual',
    section: 'menu',
  },
  {
    id: 'discounts',
    title: 'Discount Coupons',
    summary: 'Define and manage coupons to promote services.',
    content: [
      'Create coupons with codes, expirations, and discount amounts.',
      'Track usage and apply to invoices and services where supported.',
    ],
    route: '/discount-coupons',
    section: 'menu',
  },
  {
    id: 'jobs-completed',
    title: 'Jobs Completed',
    summary: 'View jobs completed with revenue and status details.',
    content: [
      'Review finished jobs, dates, and totals to reconcile with accounting.',
      'Dismiss related alerts once items are reviewed and reconciled.',
    ],
    route: '/jobs-completed',
    section: 'menu',
  },
  {
    id: 'settings',
    title: 'Settings',
    summary: 'Configure application preferences and environment parameters.',
    content: [
      'Manage environment toggles in development, mock data, and auth settings.',
      '**Remove Mock Data**: Comprehensive cleanup tool that removes all test bookings, customers, and transactions across Supabase and Local Storage.',
      'Adjust features visibility and refine operational defaults.',
      'Danger Zone includes "Restore Default Data" to reset seed measurements without losing user records.',
    ],
    route: '/settings',
    section: 'menu',
  },
  {
    id: 'reports',
    title: 'Reports',
    summary: 'Generate business reports for performance analysis.',
    content: [
      'Use filters to produce tailored insights and exports.',
      'Cross-link with invoicing and tasks data.',
      'Fully responsive tables for clear data viewing on any device.',
      'Export specialized PDFs for Customer Jobs, Inventory Value, and Employee Performance.',
    ],
    route: '/reports',
    section: 'menu',
  },
  {
    id: 'service-checklist',
    title: 'Service Checklist',
    summary: 'Start a Job, track materials, and finalize services.',
    content: [
      'Launch Start a Job to begin guided checklist steps for a vehicle.',
      'Track materials used; inventory updates on finalize when configured.',
      'Resume in-progress jobs via Active Jobs and mark completion.',
    ],
    route: '/service-checklist',
    section: 'menu',
  },
  {
    id: 'package-pricing',
    title: 'Package Pricing',
    summary: 'Manage service packages, pricing levels, and add-ons.',
    content: [
      'Edit package names, descriptions, and tiered pricing.',
      'Adjust add-ons and seasonal pricing as needed.',
      'Sync updates with website and customer tools where applicable.',
    ],
    route: '/package-pricing',
    section: 'menu',
  },
  {
    id: 'bookings',
    title: 'Bookings & Calendar',
    summary: 'Manage appointments, history, filtration, and archives.',
    content: [
      '**Hourly Timeline**: Access the new "Day View" for a detailed hour-by-hour breakdown of appointments.',
      'Bookings Calendar: View upcoming jobs. Use the top filter icon to select custom date ranges.',
      'Archiving: Completed or cancelled bookings can be archived to declutter the view.',
      'Show Archived: Use the toggle in the filter menu to show or hide archived records.',
      'Analytics: Switch to Analytics view for charts and CRM tables.',
      'Mobile Friendly: All booking lists and calendars are optimized for mobile devices.',
    ],
    route: '/bookings',
    section: 'menu',
  },
  {
    id: 'bookings-analytics',
    title: 'Booking Calendar Analytics',
    summary: 'View business performance, customer trends, and booking stats.',
    content: [
      'Access Analytics view from the Bookings page or sidebar.',
      'Use date filters to analyze specific periods.',
      'View charts for revenue, booking counts, and customer acquisition.',
      'CRM Table: Filter and manage customer bookings directly.',
    ],
    route: '/bookings', // Points to same page, user switches view
    section: 'menu',
  },
  {
    id: 'staff-schedule',
    title: 'Staff Schedule',
    summary: 'Manage employee shifts with calendar, week, and month views.',
    content: [
      '**Overview**: Create and manage employee work schedules with multiple view options.',
      '',
      '**View Modes**:',
      '• Calendar View: Monthly calendar with color-coded shifts',
      '• Week View: Detailed weekly schedule grid',
      '• Month View: Overview of entire month',
      '',
      '**Creating Shifts**:',
      '• Click any date to create a new shift',
      '• Assign employee, set start/end times',
      '• Add notes or special instructions',
      '• Color-coded by employee for easy identification',
      '',
      '**Editing Shifts**:',
      '• Click existing shift to edit',
      '• Update times, employee, or notes',
      '• Delete individual shifts with confirmation',
      '',
      '**Clear Schedule Feature (Admin Only)**:',
      '• Bulk delete shifts by time range',
      '• Options: This Week, This Month, Next Month, All Future, Custom Range',
      '• Requires PIN and typing "DELETE" for safety',
      '• Shows live count of shifts to be deleted',
      '• Cannot be undone - use with caution!',
      '',
      '**Safety Features**:',
      '✅ Individual delete confirmation for single shifts',
      '✅ PIN + DELETE confirmation for bulk clear',
      '✅ Live shift count before clearing',
      '✅ Cannot accidentally delete (multiple confirmations)',
      '',
      '**Pro Tips**:',
      '💡 Use color coding to quickly identify employee schedules',
      '💡 Week view is best for detailed planning',
      '💡 Month view is best for overview',
      '💡 Clear Schedule is useful for resetting test data or seasonal changes',
    ],
    route: '/staff-schedule',
    section: 'menu',
  },
];

export const adminDashboardTopics: HelpTopic[] = [
  {
    id: 'dashboard-alerts',
    title: 'Real‑time Alerts',
    summary: 'System alerts banner with unread counts and quick actions.',
    content: [
      'Unread alerts show for payroll due, low inventory, new files, and overdue tasks.',
      'Use Dismiss and Dismiss All to clear reviewed alerts.',
      'Alerts sync across tabs; updates trigger badges in the sidebar.',
    ],
    section: 'dashboard',
  },
  {
    id: 'dashboard-cheat-exam',
    title: 'Cheat Sheet & Exam Control',
    summary: 'Compact pill links to Exam Admin and Exam Page.',
    content: [
      'Open Cheat Sheet to generate and archive the handbook reference PDF.',
      'Exam Admin lets you manage questions and generate cheat sheet PDFs.',
      'Exam Page is the employee test; completion unlocks Certificates.',
      'Certificates page saves the training certificate PDFs to File Manager.',
    ],
    section: 'dashboard',
    route: '/exam-admin',
  },
  {
    id: 'dashboard-user-management',
    title: 'User Management',
    summary: 'Admin • Employee rights with create, edit, impersonate, delete.',
    content: [
      'Create and edit users with roles admin/employee.',
      'Impersonate users to validate role-based views.',
      'Delete users with safety confirmations.',
    ],
    section: 'dashboard',
    route: '/user-management',
  },
  {
    id: 'dashboard-settings',
    title: 'Settings (Quick Access)',
    summary: 'Open configuration to manage environment and operational preferences.',
    content: [
      'Adjust inventory, alerts, and development toggles.',
      'Use destructive actions like data deletes with caution.',
    ],
    section: 'dashboard',
    route: '/settings',
  },
  {
    id: 'dashboard-add-customer',
    title: 'Add Customer (Quick Action)',
    summary: 'Open modal to create a customer and link records.',
    content: [
      'Enter core contact data; system deduplicates by email/phone when possible.',
      'Link tasks or invoices immediately after creation.',
    ],
    section: 'dashboard',
    route: '/search-customer',
  },
  {
    id: 'dashboard-menu-visibility',
    title: 'Menu Visibility Controls',
    summary: 'Show/hide sidebar items; syncs across tabs via storage events.',
    content: [
      'Toggle checkboxes to show or hide items like Inventory, File Manager, Tasks, etc.',
      'Changes update the slide-out menu and dashboard tiles instantly.',
    ],
    section: 'dashboard',
  },
];

export const adminTopics: HelpTopic[] = [
  ...adminMenuTopics,
  ...adminDashboardTopics,
];

// Employee topics are organized into two sections per request:
// 1) Menu Items (from the slide-out menu)
// 2) Employee Dashboard items (cards and quick actions)

export const employeeMenuTopics: HelpTopic[] = [
  {
    id: 'website',
    title: 'Website',
    summary: 'View packages, add‑ons, and web tools.',
    content: [
      'Use View Website to open the public site and pricing tools.',
      'Review packages and add‑ons before discussing options with customers.',
    ],
    route: '/services',
    section: 'menu',
  },
  {
    id: 'customer-intake',
    title: 'Customer Intake Tools',
    summary: 'Sales tools to help convert prospects and guide customers.',
    content: [
      '**Overview**: Essential tools for customer-facing interactions and sales.',
      '',
      '**Package Comparison**:',
      '• Side-by-side comparison of service packages',
      '• Use as a sales tool during customer conversations',
      '• Show features and pricing clearly',
      '',
      '**Vehicle Classification**:',
      '• Categorize vehicles (sedan, SUV, truck)',
      '• Standardize pricing based on vehicle size',
      '• Link customers to classification profiles',
      '',
      '**Client Evaluation**:',
      '• Assess customer needs and vehicle condition',
      '• Guide service recommendations',
      '• Document customer requirements',
      '',
      '**Addon Upsell Script**:',
      '• Proven scripts for suggesting add-on services',
      '• Increase job value professionally',
      '• Handle objections effectively',
      '',
      '**Prospects**:',
      '• Add walk-in leads and potential customers',
      '• Track vehicle interest and contact info',
      '• Admin converts prospects to customers when they book',
      '',
      '**When to Use**:',
      '✅ During customer consultations',
      '✅ When a walk-in prospect shows interest',
      '✅ To explain service options clearly',
      '✅ To upsell services professionally',
    ],
    route: '/package-selection',
    section: 'menu',
  },
  {
    id: 'prospects',
    title: 'Prospects',
    summary: 'Capture walk-in leads and potential customers.',
    content: [
      '**Overview**: Add prospects when potential customers show interest.',
      '',
      '**Adding Prospects**:',
      '• Enter name, phone, email (name required)',
      '• Note vehicle interest and source',
      '• Save for admin to convert later',
      '',
      '**Your Role**:',
      '✅ Capture walk-in leads',
      '✅ Get contact information',
      '✅ Note what services they\'re interested in',
      '❌ Don\'t create customers (admin does this)',
      '',
      '**Workflow**:',
      '1. Potential customer shows interest',
      '2. You add them as a prospect',
      '3. Admin reviews and converts when they book',
      '',
      '**Pro Tips**:',
      '💡 Get at least name and phone number',
      '💡 Note what vehicle they have',
      '💡 Ask what services they\'re interested in',
      '💡 Admin will follow up and convert to customer',
    ],
    route: '/prospects',
    section: 'menu',
  },
  {
    id: 'service-checklist',
    title: 'Service Checklist',
    summary: 'Start jobs and track active work.',
    content: [
      '**Persistent Drafts**: Job checklists are automatically saved. You can leave and return without losing progress.',
      '**Material Tracking**: Use the "Materials Used" search to log chemical consumption during the job.',
      '**Prime Consistency**: Checklists now use the standardized Prime Essential/Elite service steps.',
      'Start Job to begin a checklist for the current task/vehicle.',
      'View Active Jobs to monitor progress and ensure consistency.',
    ],
    route: '/service-checklist',
    section: 'menu',
  },
  {
    id: 'tasks',
    title: 'Todo',
    summary: 'Your tasks with status, comments, and calendar.',
    content: [
      'See only tasks assigned to you.',
      'Update status and add comments; admins are notified automatically.',
      'Use Calendar view to plan work by day and time.',
    ],
    route: '/tasks',
    section: 'menu',
  },
  {
    id: 'customers',
    title: 'Customer Profiles',
    summary: 'Search and view customer records (view-only).',
    content: [
      '**Overview**: Look up existing customers to view their information.',
      '',
      '**What You Can Do**:',
      '✅ Search customers by name, phone, or email',
      '✅ View customer contact details',
      '✅ View customer vehicles',
      '✅ View booking history',
      '',
      '**What You Cannot Do**:',
      '❌ Create new customers (use Prospects instead)',
      '❌ Edit customer information',
      '❌ Delete customers',
      '',
      '**When to Use**:',
      '• Customer arrives for appointment',
      '• Need to look up vehicle details',
      '• Check customer history',
      '• Start service checklist',
      '',
      '**For New Customers**:',
      'If someone new shows interest, add them as a Prospect instead.',
      'Admin will convert them to a customer when they book.',
    ],
    route: '/search-customer',
    section: 'menu',
  },
  {
    id: 'quick-detailing-manual',
    title: 'Quick Detailing Manual',
    summary: 'Guidelines to maintain consistent quality.',
    content: [
      'Reference process steps and best practices quickly during work.',
      'Use this along with Rick\'s Pro Tips for better results.',
    ],
    route: '/training-manual',
    section: 'menu',
  },
  {
    id: 'employee-dashboard',
    title: 'Employee Dashboard',
    summary: 'Home base for jobs, tips, and quick actions.',
    content: [
      'Access Service Checklist, Orientation, Pro Tips, and quick actions in one place.',
      'Check Certified Detailer badge and quick stats when available.',
      'Customer Intake tools help you guide customers and capture leads.',
    ],
    route: '/employee-dashboard',
    section: 'menu',
  },
];

export const employeeDashboardTopics: HelpTopic[] = [
  {
    id: 'dashboard-service-checklist',
    title: 'SERVICE CHECKLIST',
    summary: 'Start Job • View Active Jobs • Active Jobs count.',
    content: [
      '**Persistent Progress**: Your checklists are now saved automatically; resume anytime without losing work.',
      '**Prime Packages**: Work through standardized procedures for Prime Essential and Prime Elite services.',
      '**Material Usage**: Log chemicals and materials used directly within the active checklist.',
      'Start Job begins the guided checklist for the current task/vehicle.',
    ],
    section: 'dashboard',
    route: '/service-checklist',
  },
  {
    id: 'dashboard-orientation',
    title: 'ORIENTATION',
    summary: 'Company overview • Policies • Getting started.',
    content: [
      'Orientation modal introduces company policies and expectations.',
      'Use this as a new employee to learn standards and workflows.',
    ],
    section: 'dashboard',
    route: '/employee-training',
  },
  {
    id: 'dashboard-view-website',
    title: 'VIEW WEBSITE',
    summary: 'Open public site to view package pricelist and tools.',
    content: [
      'Quickly access web pricing and add‑ons to guide the conversation.',
      'Use this with customers to present options clearly.',
    ],
    section: 'dashboard',
    route: '/services',
  },
  {
    id: 'dashboard-pro-tips',
    title: 'RICK’S PRO TIPS',
    summary: 'Quick professional reminders to reduce rework.',
    content: [
      'Check off tips as acknowledged to build consistent habits.',
      'Edit or add personal tips to improve your workflow.',
    ],
    section: 'dashboard',
  },
  {
    id: 'dashboard-quick-todo',
    title: 'Todo (Calendar)',
    summary: 'Open your tasks list and calendar view.',
    content: [
      'Use Mine, Today, Overdue, Upcoming filters to stay organized.',
      'Update status (e.g., Acknowledged) and add comments.',
    ],
    section: 'dashboard',
    route: '/tasks',
  },
  {
    id: 'dashboard-add-prospect',
    title: 'ADD PROSPECT',
    summary: 'Capture walk-in leads and potential customers.',
    content: [
      'Enter prospect name, phone, and vehicle interest.',
      'Admin will convert prospects to customers when they book.',
      'Your role is to capture leads - admin handles customer creation.',
    ],
    section: 'dashboard',
    route: '/prospects',
  },
  {
    id: 'dashboard-notify-admin',
    title: 'NOTIFY ADMIN',
    summary: 'Send a priority message; auto‑archives a PDF.',
    content: [
      'Fill subject, priority (URGENT/Normal), and message body.',
      'Sends via email and saves a PDF to File Manager.',
    ],
    section: 'dashboard',
  },
];

export const employeeTopics: HelpTopic[] = [
  ...employeeMenuTopics,
  ...employeeDashboardTopics,
];

// Customer help topics
export const customerTopics: HelpTopic[] = [
  {
    id: 'customer-dashboard',
    title: 'Customer Dashboard',
    summary: 'Your central hub for bookings, jobs, and account management.',
    content: [
      '**Welcome**: Your dashboard provides quick access to all your services and information.',
      '',
      '**Quick Stats**:',
      '• Active Jobs - Services currently in progress',
      '• Upcoming Bookings - Your scheduled appointments',
      '• Total Spent - Your lifetime spending with us',
      '• Loyalty Points - Rewards you\'ve earned',
      '',
      '**Recent Activity**:',
      '• View your last 5 bookings',
      '• Quick access to invoices',
      '• Status of ongoing jobs',
      '',
      '**Quick Actions**:',
      '• Book A Job - Schedule a new service',
      '• View Invoices - Check payment history',
      '• Contact Support - Get help anytime',
    ],
    route: '/customer-dashboard',
  },
  {
    id: 'book-a-job',
    title: 'Book A Job',
    summary: 'Schedule detailing services for your vehicle.',
    content: [
      '**How to Book**:',
      '',
      '1. Select Your Service Package',
      '   • Essential - Basic detailing',
      '   • Elite - Premium detailing',
      '   • Custom - Specialized services',
      '',
      '2. Choose Your Date & Time',
      '   • View available slots',
      '   • Select preferred time',
      '   • Add to calendar',
      '',
      '3. Add Vehicle Information',
      '   • Make, model, year',
      '   • Vehicle type',
      '   • Special requests',
      '',
      '4. Review & Confirm',
      '   • Check pricing',
      '   • Apply discount codes',
      '   • Submit booking',
      '',
      '**Booking Status**:',
      '• Pending - Awaiting confirmation',
      '• Confirmed - Scheduled and ready',
      '• In Progress - Service underway',
      '• Completed - Job finished',
      '',
      '**Cancellation Policy**:',
      '• 24 hours notice required',
      '• Full refund if eligible',
      '• Contact support to cancel',
    ],
    route: '/book',
  },
  {
    id: 'active-jobs',
    title: 'Active Jobs',
    summary: 'Track services currently in progress.',
    content: [
      '**Overview**: See all jobs being performed on your vehicles.',
      '',
      '**Job Information**:',
      '• Service type and package',
      '• Assigned technician',
      '• Start time and duration',
      '• Current status/progress',
      '',
      '**Real-Time Updates**:',
      '• Receive notifications as work progresses',
      '• View photos during service',
      '• Communication with technician',
      '',
      '**After Completion**:',
      '• Review before/after photos',
      '• Rate the service',
      '• Leave feedback',
      '• Download invoice',
    ],
    route: '/active-jobs',
  },
  {
    id: 'job-history',
    title: 'Job History',
    summary: 'View all past services and details.',
    content: [
      '**Your History**: Complete record of all services performed.',
      '',
      '**What You Can See**:',
      '• Service dates and times',
      '• Service packages used',
      '• Total costs',
      '• Technician names',
      '• Before/after photos',
      '',
      '**Features**:',
      '• Search by date or vehicle',
      '• Filter by service type',
      '• Download invoices',
      '• Re-book same service',
      '',
      '**Photo Gallery**:',
      '• View all before/after photos',
      '• Download your photos',
      '• Share on social media',
    ],
    route: '/job-history',
  },
  {
    id: 'my-invoices',
    title: 'My Invoices',
    summary: 'View and manage your billing and payments.',
    content: [
      '**Invoice Management**: Access all your billing documents.',
      '',
      '**Invoice Details**:',
      '• Service descriptions',
      '• Itemized costs',
      '• Taxes and fees',
      '• Payment status',
      '• Due dates',
      '',
      '**Payment Options**:',
      '• Pay online securely',
      '• Print for records',
      '• Download PDF copies',
      '• Set up auto-pay',
      '',
      '**Payment History**:',
      '• Track all payments',
      '• View payment methods',
      '• Get receipts',
      '',
      '**Overdue Notices**:',
      '• Automatic reminders',
      '• Payment plans available',
      '• Contact support if needed',
    ],
    route: '/my-invoices',
  },
  {
    id: 'payments-cart',
    title: 'Payments & Cart',
    summary: 'Manage your shopping cart and process payments.',
    content: [
      '**Shopping Cart**: Add services and products before checkout.',
      '',
      '**Cart Features**:',
      '• Add multiple services',
      '• Apply discount codes',
      '• View total before paying',
      '• Save cart for later',
      '',
      '**Payment Methods**:',
      '• Credit/Debit cards',
      '• Digital wallets',
      '• Bank transfers',
      '• Payment plans',
      '',
      '**Checkout Process**:',
      '1. Review cart items',
      '2. Enter payment information',
      '3. Apply discounts if available',
      '4. Confirm and pay',
      '5. Receive confirmation email',
      '',
      '**Security**:',
      '• Secure payment processing',
      '• Encrypted transactions',
      '• PCI compliant',
    ],
    route: '/payments-cart',
  },
  {
    id: 'personal-notes',
    title: 'Personal Notes',
    summary: 'Keep private notes about your vehicles and services.',
    content: [
      '**Your Notes**: Personal space for vehicle information and reminders.',
      '',
      '**What to Note**:',
      '• Vehicle maintenance reminders',
      '• Special requests for services',
      '• Preferred products or techniques',
      '• Areas needing attention',
      '',
      '**Features**:',
      '• Rich text editing',
      '• Attach photos',
      '• Set reminders',
      '• Tag by vehicle',
      '',
      '**Privacy**:',
      '• Only you can see your notes',
      '• Sync across devices',
      '• Automatic backup',
    ],
    route: '/notes',
  },
  {
    id: 'contact-support',
    title: 'Contact Support',
    summary: 'Get help from our customer service team.',
    content: [
      '**We\'re Here to Help**: Multiple ways to reach us.',
      '',
      '**Contact Methods**:',
      '• Contact form on website',
      '• Email support',
      '• Phone support',
      '• Submit a ticket',
      '',
      '**Availability**:',
      '• We operate by appointment only',
      '• Contact us to schedule',
      '• We\'ll respond as soon as possible',
      '',
      '**Common Topics**:',
      '• Booking questions',
      '• Payment issues',
      '• Service inquiries',
      '• Account management',
      '• Technical problems',
      '',
      '**Response Time**:',
      '• Email: Within 24-48 hours',
      '• Phone: Leave a message, we\'ll call back',
      '• Best way: Use the contact form',
    ],
    route: '/contact-support',
  },
  {
    id: 'prime-blog',
    title: 'Prime Blog',
    summary: 'Tips, news, and updates about vehicle care.',
    content: [
      '**Our Blog**: Learn about detailing and car care.',
      '',
      '**Content Categories**:',
      '• Detailing tips',
      '• Product reviews',
      '• Company news',
      '• Seasonal advice',
      '• Customer stories',
      '',
      '**Features**:',
      '• Subscribe to updates',
      '• Comment on posts',
      '• Share articles',
      '• Save favorites',
      '',
      '**Popular Topics**:',
      '• How to maintain your detail',
      '• Winter car care tips',
      '• Interior cleaning guides',
      '• Product recommendations',
    ],
    route: '/blog',
  },
  {
    id: 'user-settings',
    title: 'User Settings',
    summary: 'Manage your account preferences and profile.',
    content: [
      '**Account Settings**: Customize your experience.',
      '',
      '**Profile Information**:',
      '• Update contact details',
      '• Change password',
      '• Manage vehicles',
      '• Set preferences',
      '',
      '**Notifications**:',
      '• Email preferences',
      '• SMS alerts',
      '• Push notifications',
      '• Booking reminders',
      '',
      '**Privacy**:',
      '• Data management',
      '• Marketing preferences',
      '• Account deletion',
      '',
      '**Preferences**:',
      '• Default vehicle',
      '• Favorite services',
      '• Preferred technicians',
      '• Payment methods',
    ],
    route: '/user-settings',
  },
];

export function makeToc(role: 'admin' | 'employee' | 'customer', _blockedIds: string[] = []): HelpTopic[] {
  if (role === 'admin') {
    const mainMenu: HelpTopic = {
      id: 'main-menu',
      title: 'Main Menu',
      summary: 'Complete admin guide with all features and routes.',
      content: [
        'Use the table of contents to navigate quickly.',
        'Previous/Next buttons let you read through in order.',
      ],
    };
    return [mainMenu, ...adminTopics];
  }

  if (role === 'customer') {
    const welcome: HelpTopic = {
      id: 'welcome',
      title: 'Welcome to Prime Auto Detail',
      summary: 'Your guide to using our customer portal.',
      content: [
        'Welcome! This help guide will show you how to use all features of your customer account.',
        'Use the menu above to browse topics, or search for specific information.',
        'We\'re here to make your experience easy and enjoyable!',
      ],
    };
    return [welcome, ...customerTopics];
  }

  // Employees: only show requested items in two sections
  return [...employeeMenuTopics, ...employeeDashboardTopics];
}
