export type HelpTopic = {
  id: string;
  title: string;
  summary: string;
  content: string[];
  blockable?: boolean; // If true, topic can be hidden from employees unless granted
  route?: string;
  section?: 'menu' | 'dashboard';
};

// Admin help split into full coverage of slide-out Menu and Admin Dashboard actions
export const adminMenuTopics: HelpTopic[] = [
  {
    id: 'admin-dashboard',
    title: 'Admin Dashboard',
    summary: 'Central control hub for alerts, jobs, KPIs, and quick admin actions.',
    content: [
      'Overview cards show unpaid invoices, inventory alerts, task updates, and file changes.',
      'Quick links provide access to Customer profiles, Invoicing, Accounting, Payroll, Inventory, File Manager, Reports, and more.',
      '**Scenario Builder**: Quick access shortcut in the top right to create custom pricing quotes.',
      'Menu Visibility Controls allow hiding or showing dashboard tiles in the sidebar and menus.',
      'User Administration provides full user management: create, update, impersonate, and delete employees.',
      'Employee Management modal focuses on employee operations with search and edit capabilities.',
      'Web Administration integrates vehicle types, FAQs, contact info, and About sections management.',
      '**Phone Assistant**: Direct access to branded scenario scripts and consistent package inclusions.',
    ],
    route: '/admin-dashboard',
    section: 'menu',
  },
  {
    id: 'customers',
    title: 'Customers',
    summary: 'Manage customer profiles, search, and related records.',
    content: [
      'Create and update customer profiles including contact details and service history.',
      'Search and link invoices and tasks to customers.',
      'Import and export customer data using provided tools.',
      '**Archiving**: You can archive inactive customers using the "Archive" button. Toggle "Show Archived" to view or restore them.',
    ],
    route: '/search-customer',
    section: 'menu',
  },
  {
    id: 'prospects',
    title: 'Prospects',
    summary: 'Track potential clients and convert them to customers.',
    content: [
      'Add new prospects and track their vehicle interest and source.',
      'Convert prospects to full customers with one click when they book a job.',
      '**Archiving**: Archive prospects that are no longer active. Use the "Show Archived" filter to manage them.',
      'Generate PDF reports of your current prospect list.',
    ],
    route: '/prospects',
    section: 'menu',
  },
  {
    id: 'invoicing',
    title: 'Invoicing',
    summary: 'Generate and manage invoices, review payment status.',
    content: [
      'Create invoices from jobs; edit line items and taxes.',
      'Track unpaid invoices and follow up via alerts or email.',
      'Export summaries for accounting and reporting needs.',
    ],
    route: '/invoicing',
    section: 'menu',
  },
  {
    id: 'estimates',
    title: 'Estimates',
    summary: 'Manage inbound estimate requests and outbound quotes.',
    content: [
      'Inbound requests from "Book Now" auto-generate PDFs in File Manager.',
      'Review request details, convert to jobs, or communicate with customers.',
      'System simulates emails for local testing and archives them.',
    ],
    route: '/estimates',
    section: 'menu',
  },
  {
    id: 'accounting',
    title: 'Accounting',
    summary: 'View revenue reports and reconcile with completed jobs.',
    content: [
      'Review KPIs such as total revenue and job statuses.',
      'Generate period-based summaries for business insights.',
      'Integrate with invoicing data for consistency.',
    ],
    route: '/accounting',
    section: 'menu',
  },
  {
    id: 'company-budget',
    title: 'Company Budget',
    summary: 'Track expenses, visualize P/L status, and monitor monthly timelines.',
    content: [
      'Visual P/L cards use green/red/blue coding for instant status recognition.',
      'Input fixed and variable costs to forecast profitability.',
      'Responsive line graphs allow monthly timeline tracking on all devices.',
    ],
    route: '/company-budget',
    section: 'menu',
  },
  {
    id: 'payroll',
    title: 'Payroll',
    summary: 'Manage employee payouts, hours, and job-based compensation.',
    content: [
      'Record hours and track job completions that affect pay.',
      'Dismiss related alerts when records are reviewed.',
      'Export payroll summaries.',
    ],
    route: '/payroll',
    section: 'menu',
  },
  {
    id: 'inventory-control',
    title: 'Inventory Control',
    summary: 'Track chemical/material levels, view usage history, and manage tools.',
    content: [
      'Dashboards show stock levels with low-stock alerts.',
      'Usage History tracks all consumption automatically from Jobs.',
      "Material Updates: Use the 'Material Updates' button to log bulk usage or adjustments (e.g. spills, restock) not tied to a specific job.",
      'Edit History: Click any Usage history item to view or edit notes.',
    ],
    route: '/inventory-control',
    section: 'menu',
  },
  {
    id: 'inventory',
    title: 'Inventory Control',
    summary: 'Maintain supply levels, set thresholds, and track usage.',
    content: [
      'Monitor critical inventory counts and restock reminders in alerts.',
      '**Strict Classification**: Items must be explicitly marked as "Tool" (Assets/Equipment) or "Material" (Consumables/Supplies).',
      '**Lifecycle Distinction**: Assets are durable/long-term; Consumables are one-time use or depletable.',
      '**Powered Equipment**: All powered machinery must be classified as a Tool for proper maintenance tracking.',
      'Update item details and categories with unified modals.',
      'Link inventory usage to jobs for accurate tracking.',
      'Responsive tables ensure full visibility on mobile devices.',
    ],
    route: '/inventory-control',
    section: 'menu',
  },
  {
    id: 'file-manager',
    title: 'File Manager',
    summary: 'Archive PDFs and documents like employee communications and certificates.',
    content: [
      'Save generated PDFs from Employee Contact and Certificates flows.',
      'Use alerts to track new files; dismiss when reviewed.',
      'Organize files by folder paths and metadata for quick retrieval.',
      'Responsive layout ensures file lists are accessible on any device.',
      'New automated folders for Estimates, Vehicle Classifications, and Inventory Reports.',
    ],
    route: '/file-manager',
    section: 'menu',
  },
  {
    id: 'team-chat',
    title: 'Team Chat',
    summary: 'Real-time messaging for the whole team and guest users.',
    content: [
      'Direct Messages: Private secure chats between employees and admins.',
      'Group Chat: General channels for team-wide announcements.',
      'Guest Chat: Communicate with customers or guests via secure links.',
      'Notifications: Badges indicate unread messages instantly.',
    ],
    route: '/team-chat',
    section: 'menu',
  },
  {
    id: 'tasks',
    title: 'Tasks (Todo)',
    summary: 'Plan work with multi-assignee tasks, comments, statuses, and read receipts.',
    content: [
      'Create tasks via quick add or detailed editor; set priority and due dates.',
      'Assign one or more employees; employees see only their assigned tasks.',
      'Use Kanban, List, or Calendar views and filters like Mine, Overdue, Today, Upcoming.',
      'Employees update status and post comments; admins get alerts on comments and completion.',
      'Read receipts capture who has viewed tasks and when.',
    ],
    route: '/tasks',
    section: 'menu',
  },
  {
    id: 'alerts',
    title: 'Alerts & Notifications',
    summary: 'System alerts for admins and employee notifications underpin proactive workflows.',
    content: [
      'Admin alerts include overdue tasks, todo updates and comments, and file manager events.',
      'Employee notifications deliver direct notice for new/updated task assignments.',
      'Notification Bell shows unread counts and provides quick navigation.',
    ],
    section: 'menu',
  },
  {
    id: 'users-roles',
    title: 'Users & Roles',
    summary: 'Centralized user management for admins, employees, customers, and prospects.',
    content: [
      '**Overview**: Manage all user types in one place with quick creation, deletion, and overview stats.',
      '**5 Stats Cards**: View counts for Admins (🟡), Employees (🔵), Customers (🟣), Prospects (🟠), and Total Users (🟢).',
      '**Refresh Button**: Manually refresh all user data anytime with visual loading indicator.',
      '',
      '**When to Use Users & Roles**:',
      '✅ Quick user creation (any type)',
      '✅ Delete users safely',
      '✅ View stats and overview',
      '✅ Bulk management tasks',
      '',
      '**Administrators Section (🟡 Amber)**:',
      '• Create admins via Edge Function (secure)',
      '• View admin list with roles and last update',
      '• Delete admins with confirmation',
      '• Search admins by name or email',
      '',
      '**Employees Section (🔵 Blue)**:',
      '• Onboard new employees quickly',
      '• Edit employee details inline',
      '• Delete employees with confirmation',
      '• Search employees by name or email',
      '',
      '**Customers Section (🟣 Purple)**:',
      '• Add customers with name, email, phone',
      '• Edit button navigates to Customer Profiles page',
      '• Delete customers (checks for vehicles first)',
      '• Search customers by name or email',
      '',
      '**Prospects Section (🟠 Orange)**:',
      '• Add prospects for lead tracking',
      '• Edit button navigates to Prospects page',
      '• Delete prospects (checks for vehicles first)',
      '• Search prospects by name or email',
      '',
      '**Safety Features**:',
      '✅ Delete Protection: Cannot delete customers/prospects with linked vehicles',
      '✅ Confirmation Dialogs: Always asks before deleting',
      '✅ Helpful Errors: Shows exactly what\'s wrong (e.g., "Customer has 3 vehicles linked")',
      '✅ Auto-Refresh: Tables update after creation/deletion',
      '',
      '**When NOT to Use Users & Roles**:',
      '❌ Detailed customer information → Use Customer Profiles',
      '❌ Vehicle management → Use Customer Profiles',
      '❌ Lead tracking/conversion → Use Prospects page',
      '❌ HR tasks/payroll → Use Company Employees',
      '',
      '**Pro Tips**:',
      '💡 Use Users & Roles for quick adds, dedicated pages for detailed work',
      '💡 Edit buttons navigate to the appropriate detailed page',
      '💡 Search works across all sections simultaneously',
      '💡 Color coding helps identify user types at a glance',
    ],
    route: '/user-management',
    section: 'menu',
  },
  {
    id: 'user-management-quick-tips',
    title: 'User Management - Quick Tips',
    summary: 'Quick reference guide for when to use each user management page.',
    content: [
      '**When to Use Each Page**:',
      '',
      '**🎯 Users & Roles (Operations Menu)**',
      'Use for: Quick admin tasks',
      '✅ Add new users (any type)',
      '✅ Delete users',
      '✅ View stats/overview',
      '✅ Bulk management',
      '❌ Don\'t use for: Detailed info, vehicles, bookings',
      '',
      '**👥 Customer Profiles**',
      'Use for: Customer details',
      '✅ Search customers',
      '✅ Manage vehicles',
      '✅ View booking history',
      '✅ Detailed customer info',
      '',
      '**🎯 Prospects**',
      'Use for: Sales & leads',
      '✅ Track leads',
      '✅ Lead source tracking',
      '✅ Follow-up management',
      '✅ Convert to customers',
      '',
      '**💼 Company Employees**',
      'Use for: HR tasks',
      '✅ Employee details',
      '✅ Contact information',
      '✅ Payroll management',
      '✅ Role management',
      '',
      '**Quick Reference**:',
      '• Add a new customer quickly → Users & Roles',
      '• Find customer\'s vehicles → Customer Profiles',
      '• Delete test data → Users & Roles',
      '• Track a lead → Prospects',
      '• Convert prospect to customer → Prospects',
      '• View employee pay rate → Company Employees',
      '• See user stats → Users & Roles',
      '• Search for a customer → Customer Profiles',
      '',
      '**Color Guide**:',
      '🟡 Amber = Admins',
      '🔵 Blue = Employees',
      '🟣 Purple = Customers',
      '🟠 Orange = Prospects',
      '🟢 Emerald = Total',
      '',
      '**Safety Features**:',
      '✅ Delete Protection - Can\'t delete customers/prospects with vehicles',
      '✅ Confirmation Dialogs - Always asks before deleting',
      '✅ Refresh Button - Manual data refresh anytime',
      '✅ Search Filters - Find users quickly',
      '',
      '**Pro Tips**:',
      '💡 Deleting Customers: If you get an error, they have vehicles. Delete vehicles first.',
      '💡 Prospects: Use the Prospects page for detailed lead tracking, Users & Roles for quick adds.',
      '💡 Refresh: Click the refresh button after creating users to see them immediately.',
      '💡 Navigation: Edit buttons take you to the detailed page for that user type.',
    ],
    route: '/user-management',
    section: 'menu',
  },
  {
    id: 'employees',
    title: 'Company Employees',
    summary: 'Comprehensive HR management for employee details, payroll, and roles.',
    content: [
      '**Overview**: Detailed employee management beyond basic user creation.',
      '',
      '**Employee Details**:',
      '• Full contact information (address, emergency contacts)',
      '• Role and position management',
      '• Department assignments',
      '• Hire date and employment status',
      '',
      '**Payroll Management**:',
      '• Pay rates and compensation',
      '• Hours tracking',
      '• Payment history',
      '• Integration with Payroll page',
      '',
      '**Schedule & Availability**:',
      '• Work schedule preferences',
      '• Time off requests',
      '• Availability windows',
      '• Integration with Staff Schedule',
      '',
      '**Performance & Notes**:',
      '• Performance reviews',
      '• Manager notes',
      '• Training completion',
      '• Certification tracking',
      '',
      '**When to Use Company Employees**:',
      '✅ HR tasks and employee records',
      '✅ Payroll and compensation',
      '✅ Detailed contact information',
      '✅ Performance management',
      '',
      '**When to Use Users & Roles Instead**:',
      '✅ Quick employee creation',
      '✅ Simple deletion',
      '✅ Overview stats',
      '',
      '**Features**:',
      'Create employees with comprehensive details',
      'Edit all employee information',
      'Impersonate employees to test role-based views',
      'Delete employees with confirmations',
      'Search and filter employee list',
      '',
      '**Integration**:',
      '• Links to Payroll for payment processing',
      '• Links to Staff Schedule for shift management',
      '• Links to Tasks for work assignments',
      '• Links to Training for certification tracking',
    ],
    route: '/company-employees',
    section: 'menu',
  },
  {
    id: 'website-admin',
    title: 'Website Administration',
    summary: 'Manage website-facing content: vehicle types, FAQs, contact info, and About.',
    content: [
      'Edit vehicle type catalog including names, descriptions, and pricing flags.',
      'Maintain FAQ items with question and answer content.',
      'Update contact information for public site and customer communications.',
      'Add About sections to present the company coherently.',
    ],
    route: '/website-admin',
    section: 'menu',
  },
  {
    id: 'vehicle-classification',
    title: 'Vehicle Classification',
    summary: 'Define vehicle sizes and pricing multipliers.',
    content: [
      'Categorize vehicles (sedan, SUV, truck) to standardize pricing.',
      'Export classification lists to PDF for shop reference.',
      'Link customers to specific classification profiles for accurate quoting.',
    ],
    route: '/vehicle-classification',
    section: 'menu',
  },
  {
    id: 'package-selection',
    title: 'Package Comparison Guide',
    summary: 'Visual aid for explaining service packages to clients.',
    content: [
      '**Prime Tier System**: Displays the standardized Prime Essential and Prime Elite tiers.',
      'Side-by-side comparison of features, pricing, and "What\'s Included".',
      '**Dynamic Sync**: Package details are pulled from the master service list, ensuring consistency between the website and admin tools.',
      'Use as a sales tool during client intake or phone calls.',
    ],
    route: '/package-selection',
    section: 'menu',
  },
  {
    id: 'website',
    title: 'Website',
    summary: 'Open the public site to view packages, add-ons, and tools.',
    content: [
      '**Prime Tiers**: The public site features the standardized Prime Essential and Prime Elite tiers.',
      '**Avg. Time Display**: Customers can see the "Average Time" for each package in the "Learn More" modals.',
      '**Booking Integration**: The search and selection process in the Book Now flow is fully synchronized with admin pricing.',
      'Use this entry to quickly access the public pricing and services pages.',
    ],
    route: '/',
    section: 'menu',
  },
  {
    id: 'training',
    title: 'Training & Exams',
    summary: 'Provide courses, exams, and orientation materials for employees.',
    content: [
      'Orientation modal outlines company overview, policies, and getting started guides.',
      'Training Manual and Exam flows reinforce best practices and certify employees.',
      'Certificates can be generated and archived in File Manager.',
    ],
    route: '/training-manual',
    section: 'menu',
  },
  {
    id: 'discounts',
    title: 'Discount Coupons',
    summary: 'Define and manage coupons to promote services.',
    content: [
      'Create coupons with codes, expirations, and discount amounts.',
      'Track usage and apply to invoices and services where supported.',
    ],
    route: '/discount-coupons',
    section: 'menu',
  },
  {
    id: 'jobs-completed',
    title: 'Jobs Completed',
    summary: 'View jobs completed with revenue and status details.',
    content: [
      'Review finished jobs, dates, and totals to reconcile with accounting.',
      'Dismiss related alerts once items are reviewed and reconciled.',
    ],
    route: '/jobs-completed',
    section: 'menu',
  },
  {
    id: 'settings',
    title: 'Settings',
    summary: 'Configure application preferences and environment parameters.',
    content: [
      'Manage environment toggles in development, mock data, and auth settings.',
      '**Remove Mock Data**: Comprehensive cleanup tool that removes all test bookings, customers, and transactions across Supabase and Local Storage.',
      'Adjust features visibility and refine operational defaults.',
      'Danger Zone includes "Restore Default Data" to reset seed measurements without losing user records.',
    ],
    route: '/settings',
    section: 'menu',
  },
  {
    id: 'reports',
    title: 'Reports',
    summary: 'Generate business reports for performance analysis.',
    content: [
      'Use filters to produce tailored insights and exports.',
      'Cross-link with invoicing and tasks data.',
      'Fully responsive tables for clear data viewing on any device.',
      'Export specialized PDFs for Customer Jobs, Inventory Value, and Employee Performance.',
    ],
    route: '/reports',
    section: 'menu',
  },
  {
    id: 'service-checklist',
    title: 'Service Checklist',
    summary: 'Start a Job, track materials, and finalize services.',
    content: [
      'Launch Start a Job to begin guided checklist steps for a vehicle.',
      'Track materials used; inventory updates on finalize when configured.',
      'Resume in-progress jobs via Active Jobs and mark completion.',
    ],
    route: '/service-checklist',
    section: 'menu',
  },
  {
    id: 'package-pricing',
    title: 'Package Pricing',
    summary: 'Manage service packages, pricing levels, and add-ons.',
    content: [
      'Edit package names, descriptions, and tiered pricing.',
      'Adjust add-ons and seasonal pricing as needed.',
      'Sync updates with website and customer tools where applicable.',
    ],
    route: '/package-pricing',
    section: 'menu',
  },
  {
    id: 'bookings',
    title: 'Bookings & Calendar',
    summary: 'Manage appointments, history, filtration, and archives.',
    content: [
      '**Hourly Timeline**: Access the new "Day View" for a detailed hour-by-hour breakdown of appointments.',
      'Bookings Calendar: View upcoming jobs. Use the top filter icon to select custom date ranges.',
      'Archiving: Completed or cancelled bookings can be archived to declutter the view.',
      'Show Archived: Use the toggle in the filter menu to show or hide archived records.',
      'Analytics: Switch to Analytics view for charts and CRM tables.',
      'Mobile Friendly: All booking lists and calendars are optimized for mobile devices.',
    ],
    route: '/bookings',
    section: 'menu',
  },
  {
    id: 'bookings-analytics',
    title: 'Booking Calendar Analytics',
    summary: 'View business performance, customer trends, and booking stats.',
    content: [
      'Access Analytics view from the Bookings page or sidebar.',
      'Use date filters to analyze specific periods.',
      'View charts for revenue, booking counts, and customer acquisition.',
      'CRM Table: Filter and manage customer bookings directly.',
    ],
    route: '/bookings', // Points to same page, user switches view
    section: 'menu',
  },
  {
    id: 'staff-schedule',
    title: 'Staff Schedule',
    summary: 'Manage employee shifts with calendar, week, and month views.',
    content: [
      '**Overview**: Create and manage employee work schedules with multiple view options.',
      '',
      '**View Modes**:',
      '• Calendar View: Monthly calendar with color-coded shifts',
      '• Week View: Detailed weekly schedule grid',
      '• Month View: Overview of entire month',
      '',
      '**Creating Shifts**:',
      '• Click any date to create a new shift',
      '• Assign employee, set start/end times',
      '• Add notes or special instructions',
      '• Color-coded by employee for easy identification',
      '',
      '**Editing Shifts**:',
      '• Click existing shift to edit',
      '• Update times, employee, or notes',
      '• Delete individual shifts with confirmation',
      '',
      '**Clear Schedule Feature (Admin Only)**:',
      '• Bulk delete shifts by time range',
      '• Options: This Week, This Month, Next Month, All Future, Custom Range',
      '• Requires PIN and typing "DELETE" for safety',
      '• Shows live count of shifts to be deleted',
      '• Cannot be undone - use with caution!',
      '',
      '**Safety Features**:',
      '✅ Individual delete confirmation for single shifts',
      '✅ PIN + DELETE confirmation for bulk clear',
      '✅ Live shift count before clearing',
      '✅ Cannot accidentally delete (multiple confirmations)',
      '',
      '**Pro Tips**:',
      '💡 Use color coding to quickly identify employee schedules',
      '💡 Week view is best for detailed planning',
      '💡 Month view is best for overview',
      '💡 Clear Schedule is useful for resetting test data or seasonal changes',
    ],
    route: '/staff-schedule',
    section: 'menu',
  },
];

export const adminDashboardTopics: HelpTopic[] = [
  {
    id: 'dashboard-alerts',
    title: 'Real‑time Alerts',
    summary: 'System alerts banner with unread counts and quick actions.',
    content: [
      'Unread alerts show for payroll due, low inventory, new files, and overdue tasks.',
      'Use Dismiss and Dismiss All to clear reviewed alerts.',
      'Alerts sync across tabs; updates trigger badges in the sidebar.',
    ],
    section: 'dashboard',
  },
  {
    id: 'dashboard-cheat-exam',
    title: 'Cheat Sheet & Exam Control',
    summary: 'Compact pill links to Exam Admin and Exam Page.',
    content: [
      'Open Cheat Sheet to generate and archive the handbook reference PDF.',
      'Exam Admin lets you manage questions and generate cheat sheet PDFs.',
      'Exam Page is the employee test; completion unlocks Certificates.',
      'Certificates page saves the training certificate PDFs to File Manager.',
    ],
    section: 'dashboard',
    route: '/exam-admin',
  },
  {
    id: 'dashboard-user-management',
    title: 'User Management',
    summary: 'Admin • Employee rights with create, edit, impersonate, delete.',
    content: [
      'Create and edit users with roles admin/employee.',
      'Impersonate users to validate role-based views.',
      'Delete users with safety confirmations.',
    ],
    section: 'dashboard',
    route: '/user-management',
  },
  {
    id: 'dashboard-settings',
    title: 'Settings (Quick Access)',
    summary: 'Open configuration to manage environment and operational preferences.',
    content: [
      'Adjust inventory, alerts, and development toggles.',
      'Use destructive actions like data deletes with caution.',
    ],
    section: 'dashboard',
    route: '/settings',
  },
  {
    id: 'dashboard-add-customer',
    title: 'Add Customer (Quick Action)',
    summary: 'Open modal to create a customer and link records.',
    content: [
      'Enter core contact data; system deduplicates by email/phone when possible.',
      'Link tasks or invoices immediately after creation.',
    ],
    section: 'dashboard',
    route: '/search-customer',
  },
  {
    id: 'dashboard-menu-visibility',
    title: 'Menu Visibility Controls',
    summary: 'Show/hide sidebar items; syncs across tabs via storage events.',
    content: [
      'Toggle checkboxes to show or hide items like Inventory, File Manager, Tasks, etc.',
      'Changes update the slide-out menu and dashboard tiles instantly.',
    ],
    section: 'dashboard',
  },
];

export const adminTopics: HelpTopic[] = [
  ...adminMenuTopics,
  ...adminDashboardTopics,
];

// Employee topics are organized into two sections per request:
// 1) Menu Items (from the slide-out menu)
// 2) Employee Dashboard items (cards and quick actions)

export const employeeMenuTopics: HelpTopic[] = [
  {
    id: 'website',
    title: 'Website',
    summary: 'View packages, add‑ons, and web tools.',
    content: [
      'Use View Website to open the public site and pricing tools.',
      'Review packages and add‑ons before discussing options with customers.',
    ],
    route: '/services',
    section: 'menu',
  },
  {
    id: 'customer-intake',
    title: 'Customer Intake Tools',
    summary: 'Sales tools to help convert prospects and guide customers.',
    content: [
      '**Overview**: Essential tools for customer-facing interactions and sales.',
      '',
      '**Package Comparison**:',
      '• Side-by-side comparison of service packages',
      '• Use as a sales tool during customer conversations',
      '• Show features and pricing clearly',
      '',
      '**Vehicle Classification**:',
      '• Categorize vehicles (sedan, SUV, truck)',
      '• Standardize pricing based on vehicle size',
      '• Link customers to classification profiles',
      '',
      '**Client Evaluation**:',
      '• Assess customer needs and vehicle condition',
      '• Guide service recommendations',
      '• Document customer requirements',
      '',
      '**Addon Upsell Script**:',
      '• Proven scripts for suggesting add-on services',
      '• Increase job value professionally',
      '• Handle objections effectively',
      '',
      '**Prospects**:',
      '• Add walk-in leads and potential customers',
      '• Track vehicle interest and contact info',
      '• Admin converts prospects to customers when they book',
      '',
      '**When to Use**:',
      '✅ During customer consultations',
      '✅ When a walk-in prospect shows interest',
      '✅ To explain service options clearly',
      '✅ To upsell services professionally',
    ],
    route: '/package-selection',
    section: 'menu',
  },
  {
    id: 'prospects',
    title: 'Prospects',
    summary: 'Capture walk-in leads and potential customers.',
    content: [
      '**Overview**: Add prospects when potential customers show interest.',
      '',
      '**Adding Prospects**:',
      '• Enter name, phone, email (name required)',
      '• Note vehicle interest and source',
      '• Save for admin to convert later',
      '',
      '**Your Role**:',
      '✅ Capture walk-in leads',
      '✅ Get contact information',
      '✅ Note what services they\'re interested in',
      '❌ Don\'t create customers (admin does this)',
      '',
      '**Workflow**:',
      '1. Potential customer shows interest',
      '2. You add them as a prospect',
      '3. Admin reviews and converts when they book',
      '',
      '**Pro Tips**:',
      '💡 Get at least name and phone number',
      '💡 Note what vehicle they have',
      '💡 Ask what services they\'re interested in',
      '💡 Admin will follow up and convert to customer',
    ],
    route: '/prospects',
    section: 'menu',
  },
  {
    id: 'service-checklist',
    title: 'Service Checklist',
    summary: 'Start jobs and track active work.',
    content: [
      '**Persistent Drafts**: Job checklists are automatically saved. You can leave and return without losing progress.',
      '**Material Tracking**: Use the "Materials Used" search to log chemical consumption during the job.',
      '**Prime Consistency**: Checklists now use the standardized Prime Essential/Elite service steps.',
      'Start Job to begin a checklist for the current task/vehicle.',
      'View Active Jobs to monitor progress and ensure consistency.',
    ],
    route: '/service-checklist',
    section: 'menu',
  },
  {
    id: 'tasks',
    title: 'Todo',
    summary: 'Your tasks with status, comments, and calendar.',
    content: [
      'See only tasks assigned to you.',
      'Update status and add comments; admins are notified automatically.',
      'Use Calendar view to plan work by day and time.',
    ],
    route: '/tasks',
    section: 'menu',
  },
  {
    id: 'customers',
    title: 'Customer Profiles',
    summary: 'Search and view customer records (view-only).',
    content: [
      '**Overview**: Look up existing customers to view their information.',
      '',
      '**What You Can Do**:',
      '✅ Search customers by name, phone, or email',
      '✅ View customer contact details',
      '✅ View customer vehicles',
      '✅ View booking history',
      '',
      '**What You Cannot Do**:',
      '❌ Create new customers (use Prospects instead)',
      '❌ Edit customer information',
      '❌ Delete customers',
      '',
      '**When to Use**:',
      '• Customer arrives for appointment',
      '• Need to look up vehicle details',
      '• Check customer history',
      '• Start service checklist',
      '',
      '**For New Customers**:',
      'If someone new shows interest, add them as a Prospect instead.',
      'Admin will convert them to a customer when they book.',
    ],
    route: '/search-customer',
    section: 'menu',
  },
  {
    id: 'quick-detailing-manual',
    title: 'Quick Detailing Manual',
    summary: 'Guidelines to maintain consistent quality.',
    content: [
      'Reference process steps and best practices quickly during work.',
      'Use this along with Rick\'s Pro Tips for better results.',
    ],
    route: '/training-manual',
    section: 'menu',
  },
  {
    id: 'employee-dashboard',
    title: 'Employee Dashboard',
    summary: 'Home base for jobs, tips, and quick actions.',
    content: [
      'Access Service Checklist, Orientation, Pro Tips, and quick actions in one place.',
      'Check Certified Detailer badge and quick stats when available.',
      'Customer Intake tools help you guide customers and capture leads.',
    ],
    route: '/employee-dashboard',
    section: 'menu',
  },
];

export const employeeDashboardTopics: HelpTopic[] = [
  {
    id: 'dashboard-service-checklist',
    title: 'SERVICE CHECKLIST',
    summary: 'Start Job • View Active Jobs • Active Jobs count.',
    content: [
      '**Persistent Progress**: Your checklists are now saved automatically; resume anytime without losing work.',
      '**Prime Packages**: Work through standardized procedures for Prime Essential and Prime Elite services.',
      '**Material Usage**: Log chemicals and materials used directly within the active checklist.',
      'Start Job begins the guided checklist for the current task/vehicle.',
    ],
    section: 'dashboard',
    route: '/service-checklist',
  },
  {
    id: 'dashboard-orientation',
    title: 'ORIENTATION',
    summary: 'Company overview • Policies • Getting started.',
    content: [
      'Orientation modal introduces company policies and expectations.',
      'Use this as a new employee to learn standards and workflows.',
    ],
    section: 'dashboard',
    route: '/employee-training',
  },
  {
    id: 'dashboard-view-website',
    title: 'VIEW WEBSITE',
    summary: 'Open public site to view package pricelist and tools.',
    content: [
      'Quickly access web pricing and add‑ons to guide the conversation.',
      'Use this with customers to present options clearly.',
    ],
    section: 'dashboard',
    route: '/services',
  },
  {
    id: 'dashboard-pro-tips',
    title: 'RICK’S PRO TIPS',
    summary: 'Quick professional reminders to reduce rework.',
    content: [
      'Check off tips as acknowledged to build consistent habits.',
      'Edit or add personal tips to improve your workflow.',
    ],
    section: 'dashboard',
  },
  {
    id: 'dashboard-quick-todo',
    title: 'Todo (Calendar)',
    summary: 'Open your tasks list and calendar view.',
    content: [
      'Use Mine, Today, Overdue, Upcoming filters to stay organized.',
      'Update status (e.g., Acknowledged) and add comments.',
    ],
    section: 'dashboard',
    route: '/tasks',
  },
  {
    id: 'dashboard-add-prospect',
    title: 'ADD PROSPECT',
    summary: 'Capture walk-in leads and potential customers.',
    content: [
      'Enter prospect name, phone, and vehicle interest.',
      'Admin will convert prospects to customers when they book.',
      'Your role is to capture leads - admin handles customer creation.',
    ],
    section: 'dashboard',
    route: '/prospects',
  },
  {
    id: 'dashboard-notify-admin',
    title: 'NOTIFY ADMIN',
    summary: 'Send a priority message; auto‑archives a PDF.',
    content: [
      'Fill subject, priority (URGENT/Normal), and message body.',
      'Sends via email and saves a PDF to File Manager.',
    ],
    section: 'dashboard',
  },
];

export const employeeTopics: HelpTopic[] = [
  ...employeeMenuTopics,
  ...employeeDashboardTopics,
];

export function makeToc(role: 'admin' | 'employee', _blockedIds: string[] = []): HelpTopic[] {
  if (role === 'admin') {
    const mainMenu: HelpTopic = {
      id: 'main-menu',
      title: 'Main Menu',
      summary: 'Complete admin guide with all features and routes.',
      content: [
        'Use the table of contents to navigate quickly.',
        'Previous/Next buttons let you read through in order.',
      ],
    };
    return [mainMenu, ...adminTopics];
  }
  // Employees: only show requested items in two sections
  return [...employeeMenuTopics, ...employeeDashboardTopics];
}
