export const intakeWorkflowsTopic: HelpTopic = {
  id: 'intake-workflows',
  title: 'End-to-End Online Booking Workflow',
  summary: 'The complete process from start to finish of when a customer puts in an online booking all the way through to final retention.',
  content: [
    '**The Complete Online Booking Workflow (Start to Finish)**',
    'This guide outlines your exact responsibilities and the system\\'s automated actions from the moment a customer submits an online booking until their final payment and retention follow-up.',
    '',
    '🌐 **PHASE 1: The Request (Public Submission)**',
    '• **Action:** The customer submits the "Book Now" form on your public website.',
    '• **System Automation:** The system automatically checks the database to prevent duplicates (matching Email → Name → Phone). If the customer is brand new, it silently creates a **Prospect** profile for them. The booking is added to your calendar with a **Tentative (Yellow)** status. An instant in-app notification rings your Admin Bell, and an alert email is sent to your inbox.',
    '• **Your Responsibility:** Check your notification bell. Open the new booking in your Bookings page or the Prospect\\'s profile to review the requested package, vehicle size, and any reported vehicle conditions.',
    '',
    '📝 **PHASE 2: Assessment & Estimates (Optional but Recommended)**',
    '• **Action:** You review the job requirements.',
    '• **Your Responsibility:**',
    '  - **Standard Job:** If the requested service and price look perfectly standard, you can skip straight to Phase 3.',
    '  - **Custom Job:** If the vehicle requires heavy detailing (e.g., they selected "Poor" condition) or you need to formalize a custom quote, navigate to the **Estimates** page. Generate an official Estimate using the details from their booking and email it to them via the Engagement Hub. This action is permanently logged in their timeline.',
    '',
    '✅ **PHASE 3: Approval & Confirmation**',
    '• **Action:** The job is formally accepted.',
    '• **Your Responsibility:** Open the **Edit Booking** modal. Change the booking status from *Tentative* to **Confirmed (Green)**. Click the **Approve & Email** button. This sends the customer a professional confirmation email locking in their date, time, and service expectations.',
    '• **Pro Tip:** If they were a Prospect, this is the perfect time to open their profile and toggle their status to **Customer**.',
    '',
    '🧰 **PHASE 4: Execution (Day of Service)**',
    '• **Action:** Performing the physical detail.',
    '• **Your Responsibility:** Open the **Service Checklist** for the active job. Review the **Prep Summary** to gather your exact chemicals and tools before touching the car. Click **Start Service** to start the official Job Timer. Perform the Digital Inspection (taking before photos to protect yourself against liability). Check off the service steps as you complete them.',
    '• **Crucial Step:** When the car is fully detailed, click **Finish & Complete Job**. This stops the timer, logs your labor analytics, and removes the job from your active queue.',
    '',
    '💳 **PHASE 5: Invoicing & Payment**',
    '• **Action:** Collecting your revenue.',
    '• **System Automation:** Hitting "Finish & Complete Job" in the previous step *automatically* generates a Pending Invoice for the customer.',
    '• **Your Responsibility:** Open the **Invoicing** page. Review the automatically generated invoice. Add any last-minute upcharges or discounts if needed. Send the final invoice to the customer via email. Once the customer hands you cash or the digital payment clears, mark the invoice as **Paid** in the CRM.',
    '• **Result:** Marking it Paid officially injects the revenue into your Accounting ledger and Net Profit analytics.',
    '',
    '🔄 **PHASE 6: Retention & Follow-Up**',
    '• **Action:** Turning a one-time customer into a lifetime client.',
    '• **System Automation:** The completed job is permanently bound to the customer\\'s vehicle history.',
    '• **Your Responsibility:** In 4-8 weeks, the system will flag the client in the **Follow-Up Center** as "Due for Service". Use the built-in outreach tools to send a pre-drafted 1-click email campaign to schedule their next maintenance wash, completing the business cycle!',
    '',
    '---',
    '',
    '💼 **MANUAL ENTRY (Phone / Walk-in)**',
    '1. **Always start in Customer Profiles — search first.** Even if you are certain who it is. This eliminates all duplicate problems.',
    '2. **Open their card — tap the green "Book Job" button.** Never navigate to the Bookings page directly for a known customer.',
    '3. **Fill in all job details — save the booking.** Add a booking note if anything unusual applies. Check the Booking Lifecycle panel to confirm the link is solid.',
    '4. **Back to their card — Log Activity.** "Walk-in", "Repeat customer texted me". One line is enough.',
  ],
  section: 'system',
  relatedTopicIds: ['prospect-vs-customer', 'booking-flow'],
};
